name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - c_compiler: gcc
            cpp_compiler: g++
            build_type: Release
          - c_compiler: clang
            cpp_compiler: clang++
            build_type: Release

    steps:
      - uses: actions/checkout@v4

      - name: Set build directory path
        id: vars
        run: echo "build_dir=build" >> $GITHUB_OUTPUT

      - name: Configure with CMake
        run: |
          cmake -B ${{ steps.vars.outputs.build_dir }} -S . -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build with CMake
        run: cmake --build ${{ steps.vars.outputs.build_dir }} --config ${{ matrix.build_type }}

      - name: Run mcping
        run: ./build/mcping tor.forgeban.xyz 25565
